language: cpp

os: 
  - linux

dist: trusty
sudo: required 

env:
  - PYTHON=3.5 EPPY_INTEGRATION=True ENERGYPLUS_VERSION=9.0.1 ENERGYPLUS_SHA=bb7ca4f0da ENERGYPLUS_INSTALL_VERSION=9-0-1

language: python
python:
  - "3.6"

before_install:
  # install EnergyPlus
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then EXT=dmg; PLATFORM=Darwin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then EXT=sh; PLATFORM=Linux; fi
  - ENERGYPLUS_DOWNLOAD_BASE_URL=https://github.com/NREL/EnergyPlus/releases/download/v$ENERGYPLUS_VERSION
  - ENERGYPLUS_DOWNLOAD_FILENAME=EnergyPlus-$ENERGYPLUS_VERSION-$ENERGYPLUS_SHA-$PLATFORM-x86_64
  - ENERGYPLUS_DOWNLOAD_URL=$ENERGYPLUS_DOWNLOAD_BASE_URL/$ENERGYPLUS_DOWNLOAD_FILENAME.$EXT
  - curl -SLO $ENERGYPLUS_DOWNLOAD_URL

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo chmod +x $ENERGYPLUS_DOWNLOAD_FILENAME.$EXT;
        echo "y\r" | sudo ./$ENERGYPLUS_DOWNLOAD_FILENAME.$EXT;
    fi
  - sudo rm $ENERGYPLUS_DOWNLOAD_FILENAME.$EXT

  # install python

  # # actiate venv
  # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then virtualenv venv; fi
  # - source venv/bin/activate;
  # - python --version;

  # coverage and testing requirements
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install pytest-cov
  - pip install codecov

install:
  - python3 setup.py install

script: py.test ./tests --cov=./ -v

after_success:
  # coverage reporting on CodeCov
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] &&
       [[ $PYTHON == 3* ]] &&
       [[ $EPPY_INTEGRATION == True ]] &&
       [[ $NUMPY == numpy ]]; then codecov; fi

